import { ArrowRight, BarChart3, BookOpen, BrainCircuit, CalendarDays, CheckCircle2, ClipboardCheck, Flame, Play, Target } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { Card, StatCard, Button } from "../components/ui";
import { useAuth } from "../store/AuthContext";
import { useExam } from "../store/ExamContext";

export function DashboardPage() {
  const { session } = useAuth(); const { active, result, start } = useExam(); const navigate = useNavigate();
  const begin = async () => { const exam = await start({ testId: "full-mock-1", testName: "Full Length Mock 01", count: 100, durationMinutes: 120 }); navigate(`/mock-tests/${exam.testId}`); };
  const average = result ? `${result.accuracy}%` : "—";
  return <div className="page dashboard"><section className="welcome-row"><div><span className="eyebrow">Tuesday study plan</span><h1>Good to see you, {session?.user.name.split(" ")[0]}.</h1><p>One focused session today compounds into calmer exam-day decisions.</p></div><div className="streak"><Flame size={22} /><div><b>3 day streak</b><span>Keep the rhythm going</span></div></div></section>
    {active && !active.submitted && <Card className="continue-card"><div><span className="eyebrow">Session safely saved</span><h2>Continue {active.title}</h2><p>Question {active.currentIndex + 1} of {active.questions.length} · your answers and timer are restored.</p></div><Link to={`/mock-tests/${active.testId}`} className="button button-primary">Resume test <Play size={16} /></Link></Card>}
    <section className="stat-grid"><StatCard label="Tests taken" value={result ? 1 : 0} detail="Build a baseline" icon={ClipboardCheck} /><StatCard label="Average accuracy" value={average} detail="Across submitted tests" icon={Target} tone="green" /><StatCard label="Best score" value={result ? `${result.score}/${result.maximumScore}` : "—"} detail="Your personal benchmark" icon={BarChart3} tone="violet" /><StatCard label="Questions banked" value="110" detail="Original practice only" icon={BookOpen} tone="amber" /></section>
    <section className="dashboard-grid"><Card className="primary-cta"><span className="eyebrow">Next up</span><h2>Full Length Mock 01</h2><p>A balanced 100-question simulation to establish your current level.</p><div className="cta-meta"><span><CalendarDays size={15} /> 120 minutes</span><span><ClipboardCheck size={15} /> 100 questions</span></div><Button onClick={begin}>Start mock <ArrowRight size={16} /></Button></Card><Card className="subject-progress"><div className="section-title"><div><span className="eyebrow">Progress map</span><h2>Make the basics automatic</h2></div><Link to="/analytics">See analytics <ArrowRight size={15} /></Link></div>{[["C Programming", 68], ["Data Structures", 54], ["DBMS", 47], ["Operating Systems", 39]].map(([label, value]) => <div className="progress-row" key={String(label)}><span>{label}</span><div><i style={{ width: `${value}%` }} /></div><b>{value}%</b></div>)}</Card></section>
    <section className="recommend-row"><div className="section-title"><div><span className="eyebrow">Choose a direction</span><h2>Keep your next session specific</h2></div></div><div className="recommend-grid"><Link to="/practice" className="recommend-card"><BrainCircuit /><b>Build a custom practice set</b><span>Filter by subject, difficulty, and time.</span><ArrowRight /></Link><Link to="/pyq" className="recommend-card"><BookOpen /><b>Browse PYQ references</b><span>Keep verified paper sources separate.</span><ArrowRight /></Link><Link to="/mistakes" className="recommend-card"><CheckCircle2 /><b>Revisit your mistakes</b><span>Turn missed concepts into strengths.</span><ArrowRight /></Link></div></section>
  </div>;
}
