import { AlertTriangle, ArrowLeft, ArrowRight, Bookmark, Check, ChevronLeft, ChevronRight, CircleHelp, Clock3, Flag, Menu, RotateCcw, Send, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Navigate, useNavigate, useParams } from "react-router-dom";
import { BookmarkButton, Button, DifficultyBadge, SourceBadge } from "../components/ui";
import { useAuth } from "../store/AuthContext";
import { useExam } from "../store/ExamContext";

function formatTime(seconds: number) { const h = Math.floor(seconds / 3600); const m = Math.floor((seconds % 3600) / 60); const s = seconds % 60; return `${h ? `${String(h).padStart(2, "0")}:` : ""}${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`; }

export function ExamPage() {
  const { id } = useParams(); const navigate = useNavigate(); const { active, answer, clearAnswer, toggleReview, setCurrentIndex, submit, bookmarks, toggleBookmark, answerStates, retryAnswer } = useExam(); const { session } = useAuth();
  const [now, setNow] = useState(Date.now()); const [showPalette, setShowPalette] = useState(false); const [showConfirm, setShowConfirm] = useState(false); const [warning, setWarning] = useState(""); const [submitError, setSubmitError] = useState("");
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, []);
  const remaining = active ? Math.max(0, Math.ceil((new Date(active.endAt).getTime() - now) / 1000)) : 0;
  useEffect(() => { if (!active || active.submitted) return; if ([900, 300, 60].includes(remaining)) setWarning(`${remaining / 60} minute${remaining === 60 ? "" : "s"} remaining. Your work is saved.`); if (remaining === 0) void handleSubmit(); }, [remaining, active?.attemptId]);
  useEffect(() => {
    if (!active || active.submitted) return;
    const onVisibility = () => { if (document.hidden) { setWarning("You left the test tab. This was logged as a practice-session event."); if (active.remote && session?.token) { const eventPath = active.remoteType === "PYQ" ? `/api/exams/${active.attemptId}/event` : `/api/mock-tests/${active.attemptId}/event`; void fetch(eventPath, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${session.token}` }, body: JSON.stringify({ type: "visibility-change" }) }); } } };
    const beforeUnload = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = "Your exam state has been saved locally."; };
    document.addEventListener("visibilitychange", onVisibility); window.addEventListener("beforeunload", beforeUnload); return () => { document.removeEventListener("visibilitychange", onVisibility); window.removeEventListener("beforeunload", beforeUnload); };
  }, [active?.attemptId, active?.remote, active?.submitted, session?.token]);
  if (!active || active.testId !== id) return <Navigate to="/mock-tests" replace />;
  if (active.submitted) return <Navigate to={`/mock-tests/${active.testId}/result`} replace />;
  const testId = active.testId; const question = active.questions[active.currentIndex]; const saved = active.answers[question.id]; const selected = saved?.selectedOptionIds ?? []; const marked = saved?.markedForReview ?? false;
  const answeredCount = Object.values(active.answers).filter((item) => item.selectedOptionIds.length > 0).length;
  const status = (index: number) => { const item = active.answers[active.questions[index].id]; if (!item) return "not-visited"; if (item.markedForReview && item.selectedOptionIds.length) return "answered-review"; if (item.markedForReview) return "review"; return item.selectedOptionIds.length ? "answered" : "not-answered"; };
  const choose = (optionId: string) => { if (question.questionType === "SINGLE") answer(question.id, [optionId]); else answer(question.id, selected.includes(optionId) ? selected.filter((id) => id !== optionId) : [...selected, optionId]); };
  const next = () => setCurrentIndex(active.currentIndex + 1); const previous = () => setCurrentIndex(active.currentIndex - 1);
  async function handleSubmit() { setSubmitError(""); try { const result = await submit(); if (result) navigate(`/mock-tests/${testId}/result`, { replace: true }); } catch { setSubmitError("We couldn't submit this exam right now. Your answers remain on this device. Please try again."); } }
  const saveState = answerStates[question.id];
  return <main className="exam-page"><header className="exam-header"><div className="exam-brand"><span className="brand-mark"><Check size={16} /></span><div><b>JECA Prep Hub</b><small>{active.title}</small></div></div><div className={`exam-timer ${remaining <= 300 ? "urgent" : ""}`} aria-live="polite"><Clock3 size={18} /><span>{formatTime(remaining)}</span></div><Button variant="danger" onClick={() => setShowConfirm(true)}>Submit test <Send size={16} /></Button></header>
    {warning && <div className="exam-warning" role="alert"><AlertTriangle size={17} />{warning}<button onClick={() => setWarning("")} aria-label="Dismiss warning"><X size={16} /></button></div>}{submitError && <div className="exam-warning" role="alert"><AlertTriangle size={17} />{submitError}</div>}{saveState === "saving" && <div className="exam-warning" role="status">Saving answer...</div>}{saveState === "saved" && <div className="exam-warning" role="status">Answer saved.</div>}{saveState === "error" && <div className="exam-warning" role="alert">Unable to save answer. <button onClick={() => retryAnswer(question.id)}>Retry</button></div>}
    <div className="exam-layout"><section className="exam-question"><div className="question-topline"><span>Question {active.currentIndex + 1} <i>of {active.questions.length}</i></span><div><SourceBadge sourceType={question.sourceType} year={question.year} /><DifficultyBadge difficulty={question.difficulty} /><BookmarkButton active={bookmarks.includes(question.id)} onClick={() => toggleBookmark(question.id)} /></div></div><article className="exam-prompt"><h1>{question.questionText}</h1>{question.questionType === "MULTIPLE" && <p className="select-hint">Select all options you believe are correct.</p>}</article><div className="exam-options" role={question.questionType === "MULTIPLE" ? "group" : "radiogroup"} aria-label="Answer choices">{question.options.map((option) => <button key={option.id} className={`exam-option ${selected.includes(option.id) ? "selected" : ""}`} onClick={() => choose(option.id)} aria-pressed={selected.includes(option.id)}><span>{question.questionType === "MULTIPLE" ? <span className="choice-check">{selected.includes(option.id) && <Check size={14} />}</span> : <span className="choice-letter">{option.id}</span>}</span><b>{option.text}</b></button>)}</div><div className="exam-topic"><CircleHelp size={16} /> {question.subject} · {question.topic}</div></section>
      <aside className={`palette ${showPalette ? "open" : ""}`}><div className="palette-head"><div><span className="eyebrow">Question navigator</span><h2>{answeredCount} answered</h2></div><button className="palette-close" onClick={() => setShowPalette(false)} aria-label="Close palette"><X /></button></div><div className="palette-grid">{active.questions.map((item, index) => <button key={`${item.id}-${index}`} className={`palette-item ${status(index)} ${index === active.currentIndex ? "current" : ""}`} onClick={() => { setCurrentIndex(index); setShowPalette(false); }} aria-label={`Question ${index + 1}, ${status(index).replace("-", " ")}`}>{index + 1}</button>)}</div><div className="palette-legend"><span><i className="legend-not-visited" />Not visited</span><span><i className="legend-not-answered" />Not answered</span><span><i className="legend-answered" />Answered</span><span><i className="legend-review" />Marked</span><span><i className="legend-answered-review" />Answered + marked</span></div></aside></div>
    <footer className="exam-footer"><button className="palette-trigger" onClick={() => setShowPalette(true)}><Menu size={18} /> Questions</button><div className="exam-actions"><Button variant="quiet" onClick={previous} disabled={active.currentIndex === 0}><ChevronLeft size={17} /> Previous</Button><Button variant="quiet" onClick={() => clearAnswer(question.id)} disabled={!selected.length}><RotateCcw size={16} /> Clear</Button><Button variant={marked ? "secondary" : "quiet"} onClick={() => toggleReview(question.id)}><Flag size={16} /> {marked ? "Unmark review" : "Mark for review"}</Button><Button onClick={next} disabled={active.currentIndex === active.questions.length - 1}>Save & next <ChevronRight size={17} /></Button></div></footer>
    {showConfirm && <div className="modal-backdrop" role="presentation"><div className="submit-modal" role="dialog" aria-modal="true" aria-labelledby="submit-title"><AlertTriangle className="modal-icon" /><h2 id="submit-title">Ready to submit?</h2><p>You have answered <b>{answeredCount}</b> of <b>{active.questions.length}</b> questions. <b>{active.questions.length - answeredCount}</b> are unanswered.</p><small>Submission is final for this attempt. You can review your answers and explanations afterwards.</small><div><Button variant="secondary" onClick={() => setShowConfirm(false)}>Keep working</Button><Button variant="danger" onClick={() => void handleSubmit()}>Submit test <Send size={16} /></Button></div></div></div>}
  </main>;
}
