import { ArrowRight, BarChart3, BookMarked, BookOpenCheck, BrainCircuit, CheckCircle2, ClipboardX, Code2, Database, Layers3, LockKeyhole, Settings2, ShieldCheck, SlidersHorizontal, UserRound } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { useEffect, useState } from "react";
import { questionBank, supportedSubjects } from "@jeca/shared/questions";
import { Button, Card, EmptyState, SourceBadge } from "../components/ui";
import { useAuth } from "../store/AuthContext";
import { useExam } from "../store/ExamContext";

export function AnalyticsPage() {
  const { result } = useExam();
  if (!result) return <div className="page"><section className="page-heading"><div><span className="eyebrow">Performance analytics</span><h1>Let your attempts tell the story.</h1><p>Submit a mock or custom practice set to unlock personal statistics.</p></div></section><EmptyState title="No submitted attempts yet" text="Your score, accuracy trend, strengths, and weak areas will appear after your first test." action={<Link to="/mock-tests" className="button button-primary">Start a mock <ArrowRight size={16} /></Link>} /></div>;
  const strongest = [...result.subjectBreakdown].sort((a, b) => b.accuracy - a.accuracy)[0]; const weakest = [...result.subjectBreakdown].sort((a, b) => a.accuracy - b.accuracy)[0];
  return <div className="page"><section className="page-heading"><div><span className="eyebrow">Performance analytics</span><h1>Your most recent learning signal.</h1><p>Use accuracy by subject alongside the answer review; scores alone do not show the whole pattern.</p></div></section><div className="stat-grid"><Card className="stat-card"><span className="stat-icon cyan"><BarChart3 /></span><div><p>Latest score</p><strong>{result.score} / {result.maximumScore}</strong><small>{result.accuracy}% accuracy</small></div></Card><Card className="stat-card"><span className="stat-icon green"><CheckCircle2 /></span><div><p>Strongest subject</p><strong>{strongest?.subject ?? "—"}</strong><small>{strongest?.accuracy ?? 0}% accuracy</small></div></Card><Card className="stat-card"><span className="stat-icon amber"><BrainCircuit /></span><div><p>Focus next</p><strong>{weakest?.subject ?? "—"}</strong><small>{weakest?.accuracy ?? 0}% accuracy</small></div></Card></div><Card className="analytics-plan"><span className="eyebrow">Suggested next step</span><h2>Turn your weakest signal into a 20-question session.</h2><p>Target {weakest?.subject ?? "a subject"}, then take another mixed mock to see if the improvement holds.</p><Link to="/practice" className="button button-primary">Build focused practice <ArrowRight size={16} /></Link></Card><Card><div className="section-title"><div><span className="eyebrow">Subject detail</span><h2>Accuracy and score</h2></div></div><div className="analytics-list">{result.subjectBreakdown.map((item) => <div key={item.subject}><div><b>{item.subject}</b><span>{item.correct} correct · {item.incorrect} incorrect · {item.unattempted} skipped</span></div><div className="analytics-progress"><i style={{ width: `${item.accuracy}%` }} /></div><b>{item.accuracy}%</b><em>{item.score}/{item.maximumScore}</em></div>)}</div></Card></div>;
}

export function BookmarksPage() {
  const { bookmarks, toggleBookmark, start } = useExam(); const navigate = useNavigate(); const saved = questionBank.filter((question) => bookmarks.includes(question.id));
  const practiceSaved = async () => { const exam = await start({ testId: "bookmarks", testName: "Bookmarked Questions", count: saved.length, durationMinutes: Math.max(10, saved.length * 2) }); navigate(`/mock-tests/${exam.testId}`); };
  return <div className="page"><section className="page-heading"><div><span className="eyebrow">Saved for later</span><h1>Your bookmarks.</h1><p>Keep the questions that deserve another thoughtful pass.</p></div></section>{saved.length ? <Card><div className="bookmark-list">{saved.map((question) => <article key={question.id}><div><SourceBadge sourceType={question.sourceType} /><h3>{question.questionText}</h3><p>{question.subject} · {question.topic}</p></div><Button variant="quiet" onClick={() => toggleBookmark(question.id)}>Remove</Button></article>)}</div><Button onClick={() => void practiceSaved()}>Practice saved questions <ArrowRight size={16} /></Button></Card> : <EmptyState title="No bookmarks yet" text="Use the bookmark icon in practice or an exam to build a revision queue." action={<Link to="/practice" className="button button-primary">Explore questions</Link>} />}</div>;
}

export function MistakesPage() { return <div className="page"><section className="page-heading"><div><span className="eyebrow">Learning loop</span><h1>My mistakes.</h1><p>Incorrect answers from completed server attempts are added here automatically.</p></div></section><EmptyState title="No mistakes in this local workspace" text="Submit a practice set or mock; wrong answers are retained for targeted retry when using the API." action={<Link to="/mock-tests" className="button button-primary">Take a mock <ArrowRight size={16} /></Link>} /></div>; }

export function SettingsPage() { const { session } = useAuth(); return <div className="page settings-page"><section className="page-heading"><div><span className="eyebrow">Learner settings</span><h1>Keep your workspace comfortable.</h1><p>Settings are deliberately calm and limited to what helps you study.</p></div></section><Card className="settings-section"><UserRound /><div><h2>Profile</h2><p>{session?.user.name} · {session?.user.email}</p></div><span className="status-pill"><CheckCircle2 size={15} /> Active</span></Card><Card className="settings-section"><SlidersHorizontal /><div><h2>Exam preferences</h2><p>Timer warnings at 15, 5, and 1 minutes · autosave enabled.</p></div><span className="status-pill"><CheckCircle2 size={15} /> On</span></Card><Card className="settings-section"><LockKeyhole /><div><h2>Privacy</h2><p>Practice visibility-change events are logged as basic session UX signals only. No invasive proctoring.</p></div></Card></div>; }

export function AdminPage() {
  const { session } = useAuth();
  const navigate = useNavigate();
  const [section, setSection] = useState<"PYQ" | "MOCK" | null>(null);
  const [years, setYears] = useState<number[]>([]);
  const [mockTests, setMockTests] = useState<Array<{ id: string; title: string; questionCount: number; durationMinutes: number }>>([]);
  useEffect(() => {
    void fetch("/api/pyq").then((response) => response.ok ? response.json() : { papers: [] }).then((payload: { papers?: Array<{ year: number }> }) => { const values = (payload.papers ?? []).map((paper) => paper.year); setYears([...new Set<number>(values)].sort((a, b) => b - a)); }).catch(() => setYears([]));
    void fetch("/api/mock-tests").then((response) => response.ok ? response.json() : { items: [] }).then((payload) => setMockTests(Array.isArray(payload.items) ? payload.items : [])).catch(() => setMockTests([]));
  }, []);
  if (session?.user.role !== "ADMIN") return <div className="page"><section className="page-heading"><div><span className="eyebrow">Protected area</span><h1>Administrator access required.</h1><p>Set an account role to ADMIN in your database before using question-management actions.</p></div></section><EmptyState title="This workspace is student-only" text="The API protects admin routes with JWT role checks." /></div>;
  return <div className="page"><section className="page-heading"><div><span className="eyebrow">Administration</span><h1>Question bank control room.</h1><p>Choose a source first, then select the paper year or mock set you want to manage.</p></div></section><div className="admin-source-grid"><button className={section === "PYQ" ? "admin-source-card selected" : "admin-source-card"} onClick={() => setSection("PYQ")}><BookOpenCheck size={25} /><span className="eyebrow">Official papers</span><h2>PYQ</h2><p>Manage questions by imported paper year while preserving original numbering and order.</p><strong>{years.length || "—"} years available</strong></button><button className={section === "MOCK" ? "admin-source-card selected" : "admin-source-card"} onClick={() => setSection("MOCK")}><Layers3 size={25} /><span className="eyebrow">Timed question sets</span><h2>Mock Tests</h2><p>Choose a deterministic mock set and edit the questions used by future attempts.</p><strong>{mockTests.length || 10} sets available</strong></button></div>{section === "PYQ" && <Card className="admin-choice-panel"><div className="section-title"><div><span className="eyebrow">PYQ</span><h2>Select paper year</h2></div><Database size={20} /></div><div className="admin-choice-grid">{years.map((year) => <button className="admin-choice" key={year} onClick={() => navigate(`/admin/questions?sourceType=PYQ&year=${year}`)}><span>{year}</span><small>Open questions</small><ArrowRight size={16} /></button>)}</div>{!years.length && <p className="admin-muted">No imported PYQ papers are available.</p>}</Card>}{section === "MOCK" && <Card className="admin-choice-panel"><div className="section-title"><div><span className="eyebrow">Mock Tests</span><h2>Select set number</h2></div><ShieldCheck size={20} /></div><div className="admin-choice-grid">{mockTests.map((mock, index) => <button className="admin-choice" key={mock.id} onClick={() => navigate(`/admin/questions?sourceType=MOCK&mockSet=${mock.id}`)}><span>Mock Test {index + 1}</span><small>{mock.questionCount} questions · {mock.durationMinutes} min</small><ArrowRight size={16} /></button>)}</div></Card>}<Card className="admin-all-questions"><Database size={19} /><div><h2>All questions</h2><p>Search and filter the complete practice, mock, and PYQ question collection.</p></div><Link to="/admin/questions" className="button button-secondary">Open all questions</Link></Card></div>;
}

export function AdminSubPage() { return <div className="page"><section className="page-heading"><div><span className="eyebrow">Admin workspace</span><h1>Manage the preparation bank.</h1><p>Question editing and safe import validation belong to the protected API surface.</p></div></section><Card className="admin-info"><ClipboardX /><div><h2>Use the API-backed admin tooling</h2><p>POST /api/questions supports validated question creation. POST /api/admin/questions/import validates CSV-mapped JSON all-or-nothing before persistence.</p></div></Card></div>; }
